export const assignmentOperator = '='
export const equalityOperator = '=='
export const inequalityOperator = '!='
export const lessThanOperator = '<'
export const lessThanEqualOperator = '<='
export const greaterThanOperator = '>'
export const greaterThanEqualOperator = '>='
